import {createCombatArena,canOccupy} from './world/arena.mjs';
import {renderWalls,hasLineOfSight} from './world/raycaster.mjs';
import {createEnemy,updateEnemy,damageEnemy,EnemyState} from './world/enemy-ai.mjs';
import {createWeaponState,tickWeapon,tryFire,startReload,finishReload,damageAtDistance,createHitMarker} from './game/combat.js';
import {CombatPresentation} from './game/presentation.js';
const $=s=>document.querySelector(s), canvas=$('#view'),ctx=canvas.getContext('2d',{alpha:false}), arena=createCombatArena();
let player={...arena.playerSpawn,health:100}, weapon=createWeaponState(), enemies=arena.enemySpawns.map((s,i)=>createEnemy(s,i,[s,{x:Math.max(1.5,s.x-2),z:s.z}]));
let keys={}, firing=false, active=false, won=false, noise=null, last=performance.now(),frames=[], recoil=0;
const audio=new (window.AudioContext||window.webkitAudioContext)(), presentation=new CombatPresentation({audioContext:audio});
function size(){const d=Math.min(devicePixelRatio,1.5);canvas.width=innerWidth*d;canvas.height=innerHeight*d} addEventListener('resize',size);size();
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyR')weapon=startReload(weapon)});addEventListener('keyup',e=>keys[e.code]=false);
canvas.addEventListener('mousedown',()=>{firing=true;canvas.requestPointerLock();audio.resume()});addEventListener('mouseup',()=>firing=false);
addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas){player.yaw+=e.movementX*.0021;recoil=Math.max(-.1,Math.min(.1,recoil+e.movementY*.0017))}});
$('#deploy').onclick=()=>{active=true;$('#menu').classList.add('hidden');canvas.requestPointerLock();audio.resume()};
document.addEventListener('pointerlockchange',()=>{if(active&&!won&&document.pointerLockElement!==canvas){$('#menu').classList.remove('hidden');active=false}});
function shoot(){let out=tryFire(weapon,17);weapon=out.state;if(!out.event)return;presentation.onShot(out.event);player.yaw+=out.event.yaw*2;recoil-=out.event.pitch*2;noise={x:player.x,z:player.z,radius:10,age:0};
 let best=null;for(const e of enemies){if(e.state===EnemyState.DEAD)continue;const dx=e.x-player.x,dz=e.z-player.z,d=Math.hypot(dx,dz),a=Math.abs(Math.atan2(Math.sin(Math.atan2(dz,dx)-player.yaw),Math.cos(Math.atan2(dz,dx)-player.yaw)));if(a<.055&&hasLineOfSight(arena,player,e)&&(!best||d<best.d))best={e,d,head:a<.018}}
 if(best){const dead=damageEnemy(best.e,damageAtDistance('viper',best.d,best.head?'head':'body'));presentation.onHit(createHitMarker(best.head?'head':'body',dead));$('#cross').classList.add('hit');setTimeout(()=>$('#cross').classList.remove('hit'),100)}}
function update(dt){weapon=tickWeapon(weapon,dt);if(weapon.reload===0)weapon=finishReload(weapon);if(firing)shoot();noise&& (noise.age+=dt);recoil*=Math.exp(-8*dt);
 const f=(keys.KeyW?1:0)-(keys.KeyS?1:0),s=(keys.KeyD?1:0)-(keys.KeyA?1:0),len=Math.max(1,Math.hypot(f,s)),spd=keys.ShiftLeft?7.3:5.4,dx=(Math.cos(player.yaw)*f+Math.cos(player.yaw+Math.PI/2)*s)/len*spd*dt,dz=(Math.sin(player.yaw)*f+Math.sin(player.yaw+Math.PI/2)*s)/len*spd*dt;if(canOccupy(arena,player.x+dx,player.z))player.x+=dx;if(canOccupy(arena,player.x,player.z+dz))player.z+=dz;
 for(const e of enemies){for(const ev of updateEnemy(e,{player,arena,noise},dt)){if(Math.random()<ev.hitChance){player.health=Math.max(0,player.health-ev.damage);$('#damage').classList.add('on');setTimeout(()=>$('#damage').classList.remove('on'),90)}}}if(player.health<=0){player.health=100;Object.assign(player,arena.playerSpawn);weapon=createWeaponState()}
 const alive=enemies.filter(e=>e.state!==EnemyState.DEAD).length;if(!alive&&Math.hypot(player.x-arena.extraction.x,player.z-arena.extraction.z)<arena.extraction.radius){won=true;active=false;document.exitPointerLock();$('#banner').textContent='MISSION COMPLETE · RELAY SECURED';$('#objective').textContent='EXTRACTION COMPLETE'}else $('#objective').textContent=alive?'ELIMINATE RELAY GUARDS':'REACH EXTRACTION BEACON';
 $('#enemies').textContent=`${alive} HOSTILE${alive===1?'':'S'}`;$('#ammo').textContent=weapon.ammo;$('#reserve').textContent=`/ ${weapon.reserve}${weapon.reload?' · RELOADING':''}`;$('#hp').textContent=player.health;$('#hpbar').style.width=player.health+'%';}
function render(){const w=canvas.width,h=canvas.height,g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#193240');g.addColorStop(.5,'#819096');g.addColorStop(.501,'#1a2020');g.addColorStop(1,'#080b0b');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);renderWalls(ctx,arena,{x:player.x,z:player.z,yaw:player.yaw+recoil},{columns:Math.min(w,900),fov:1.05});
 const sprites=[...enemies.filter(e=>e.state!==EnemyState.DEAD).map(e=>({...e,kind:'enemy'})),...(enemies.every(e=>e.state===EnemyState.DEAD)?[{...arena.extraction,kind:'extract'}]:[])];sprites.sort((a,b)=>Math.hypot(b.x-player.x,b.z-player.z)-Math.hypot(a.x-player.x,a.z-player.z));for(const e of sprites){const dx=e.x-player.x,dz=e.z-player.z,d=Math.hypot(dx,dz),a=Math.atan2(Math.sin(Math.atan2(dz,dx)-player.yaw-recoil),Math.cos(Math.atan2(dz,dx)-player.yaw-recoil));if(Math.abs(a)>.62||!hasLineOfSight(arena,player,e))continue;const x=w/2+a/1.05*w,sz=Math.min(h*.75,h/d),y=h/2;ctx.save();ctx.shadowBlur=e.kind==='extract'?28:8;ctx.shadowColor=e.kind==='extract'?'#ffb21c':'#ff304c';ctx.fillStyle=e.kind==='extract'?'#ffb21c88':'#111';ctx.fillRect(x-sz*.18,y-sz*.46,sz*.36,sz*.82);ctx.fillStyle=e.kind==='extract'?'#fff2':'#ff4058';ctx.fillRect(x-sz*.12,y-sz*.38,sz*.24,sz*.08);ctx.restore()}
 ctx.save();ctx.translate(w*.72,h*.82);ctx.rotate(-.13+recoil*.5);ctx.fillStyle='#151b1d';ctx.fillRect(-30,-20,w*.3,h*.15);ctx.fillStyle='#bd8a28';ctx.fillRect(5,-14,w*.17,8);ctx.restore();}
function loop(t){let dt=Math.min(.05,(t-last)/1000);last=t;if(active)update(dt);render();presentation.update(dt);frames.push(1/Math.max(dt,.001));if(frames.length>30)frames.shift();$('#fps').textContent=Math.round(frames.reduce((a,b)=>a+b,0)/frames.length)+' FPS';requestAnimationFrame(loop)}requestAnimationFrame(loop);
